### PR TITLE
#43 - there is not need to support list operation

### LINKED ISSUE #43: integrational test for list operation
`pip` does not seem to have specific operation to list available packages from remote repository: 
`pip list` command list installed packages, options `--index-url` or `--find-links` have no affect:
```bash
MacBook-Pro:~ alena$ python3 -m pip list
Package            Version
------------------ ---------
AlarmTime          0.1.3
bleach             3.1.5
certifi            2020.6.20
chardet            3.0.4
colorama           0.4.3
docutils           0.16
idna               2.10
importlib-metadata 1.7.0
keyring            21.2.1
packaging          20.4
peppercorn         0.6
pip                20.1.1
pkginfo            1.5.0.1
Pygments           2.6.1
pyparsing          2.4.7
readme-renderer    26.0
requests           2.24.0
requests-toolbelt  0.9.1
rfc3986            1.4.0
setuptools         49.2.0
six                1.12.0
tqdm               4.47.0
twine              3.2.0
urllib3            1.25.9
webencodings       0.5.1
wheel              0.34.2
zipp               3.1.0
```
```bash
MacBook-Pro:~ alena$ python3 -m pip list --find-links https://pypi.org/simple/alarmtime/
Package            Version
------------------ ---------
AlarmTime          0.1.3
bleach             3.1.5
certifi            2020.6.20
chardet            3.0.4
colorama           0.4.3
docutils           0.16
idna               2.10
importlib-metadata 1.7.0
keyring            21.2.1
packaging          20.4
peppercorn         0.6
pip                20.1.1
pkginfo            1.5.0.1
Pygments           2.6.1
pyparsing          2.4.7
readme-renderer    26.0
requests           2.24.0
requests-toolbelt  0.9.1
rfc3986            1.4.0
setuptools         49.2.0
six                1.12.0
tqdm               4.47.0
twine              3.2.0
urllib3            1.25.9
webencodings       0.5.1
wheel              0.34.2
zipp               3.1.0
```
```bash
MacBook-Pro:~ alena$ python3 -m pip list --index-url https://pypi.org/simple/
Package            Version
------------------ ---------
AlarmTime          0.1.3
bleach             3.1.5
certifi            2020.6.20
chardet            3.0.4
colorama           0.4.3
docutils           0.16
idna               2.10
importlib-metadata 1.7.0
keyring            21.2.1
packaging          20.4
peppercorn         0.6
pip                20.1.1
pkginfo            1.5.0.1
Pygments           2.6.1
pyparsing          2.4.7
readme-renderer    26.0
requests           2.24.0
requests-toolbelt  0.9.1
rfc3986            1.4.0
setuptools         49.2.0
six                1.12.0
tqdm               4.47.0
twine              3.2.0
urllib3            1.25.9
webencodings       0.5.1
wheel              0.34.2
zipp               3.1.0
```
To check all the available package versions it's [recommended](https://stackoverflow.com/a/26664162) use empty version tag:
```bash
MacBook-Pro:~ alena$ python3 -m pip install --index-url http://localhost:80/alena/pypi/simple alarmtime== 
Looking in indexes: http://localhost:80/alena/pypi/simple
ERROR: Could not find a version that satisfies the requirement alarmtime== (from versions: 0.1.3)
``` 
`Pip` will not install the package, but list all the available versions.

### PR DESCRIPTION
**Pull request by olenagerasimova**
To close #43 I've removed not required test and updated issue description(for more details please check it).

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/81#issuecomment-662259333))

@olenagerasimova Job `gh:artipie/pypi-adapter#81` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/81#issuecomment-662259333))

@olenagerasimova Pull request [#81](https://github.com/artipie/pypi-adapter/issues/81) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#81` is not assigned, can't get performer

**Pull request merged**
