### PR TITLE
resolve #12: add save method to the LiveMeta

### LINKED ISSUE #12: avoid duplications in packages meta

### PR DESCRIPTION
**Pull request by Guseyn**

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#15](https://github.com/artipie/pypi-adapter/issues/15) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/15#issuecomment-584060994))

@g4s8 Job `gh:artipie/pypi-adapter#15` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
