### PR TITLE
Use multipart from http

### LINKED ISSUE #159: Update http and asto
Let's update http and asto and use
- sdk api from asto to work with content as input stream when packages are read/parsed
- multipart sdk from asto in `WheelSlice`

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #159 
Used multipart from http, corrected `WheelSliceTest` and removed current multipart implementation.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 please, take a look. The problem seems to be the same, I'm saving the part to the storage, but it is corrupted.

**Comment by g4s8** [comment]
@olenagerasimova please check PR: https://github.com/olenagerasimova/pypi-adapter/pull/1

**Comment by olenagerasimova** [comment]
@g4s8 sorry, I did not understand your suggestion in the PR, test still stacks on saving part to storage

**Comment by g4s8** [comment]
@olenagerasimova it's working on my laptop, let me check it again

**Comment by olenagerasimova** [comment]
@g4s8 run the test several times, on my laptop it sometime works too and sometime get stuck

**Comment by olenagerasimova** [comment]
@g4s8 I've refactored IT in this adapter, I'd suggest to merge #165 and then try to investigate this one further

**Comment by g4s8** [comment]
@olenagerasimova I updated this branch with your latest changes in tests and now all tests passes

**Comment by olenagerasimova** [comment]
@g4s8 thanks, I see... Let's merge then

**Review by g4s8 — APPROVED** [review]

**Pull request merged**
