### PR TITLE
#74 - Do not loose path in WheelSlice

### PR DESCRIPTION
**Pull request by olenagerasimova**
Fixed `WheelSlice` to save content with respect to the request path and added corresponding test.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@carlosmiranda fixed, thanks

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@carlosmiranda please make sure you will find at least  issues during next CR, thanks

**Comment by carlosmiranda** [comment]
@sereshqua confirmed, thanks

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
