### PR TITLE
#82 - IT with denormalized python project name

### LINKED ISSUE #82: Integration test with denormalized project name
Add integration test with denormalized python project name.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Added integration test with denormalized python project name to close #82, also fixed regex in `NormalizedProjectName`.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/83#issuecomment-662271298))

@olenagerasimova Job `gh:artipie/pypi-adapter#83` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/83#issuecomment-662271298))

@olenagerasimova Pull request [#83](https://github.com/artipie/pypi-adapter/issues/83) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#83` is not assigned, can't get performer

**Pull request merged**
