### PR TITLE
#79 - RedirectSlice introduced

### PR DESCRIPTION
**Pull request by olenagerasimova**
Introduced `RedirectSlice` for #79 and used it in `PySlice`.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/84#issuecomment-662921892))

@olenagerasimova Job `gh:artipie/pypi-adapter#84` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/pypi-adapter/issues/84#issuecomment-662921892))

@olenagerasimova Pull request [#84](https://github.com/artipie/pypi-adapter/issues/84) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/pypi-adapter#84` is not assigned, can't get performer

**Pull request merged**
