### PR TITLE
#68 - extended SliceIndexTest

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #68 I've got rid of substorage usage in `SliceIndex` and extended `SliceIndexTest`.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
This implementation of `SliceIndex` not suitable for `pip`, closing

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Pull request [#69](https://github.com/artipie/pypi-adapter/issues/69) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request closed without merging**
